const path = require('path');
const out = process.argv[2];
const { hotp, base32Encode, base32Decode, matchTotp, currentStep } = require(path.join(out, 'auth', 'totp.js'));
const { encrypt, decrypt, safeEqual } = require(path.join(out, 'common', 'crypto.js'));
const results = [];
const check = (name, ok) => results.push(`${ok ? 'PASS' : 'FAIL'}  ${name}`);
const secret = Buffer.from('12345678901234567890');
const expected = ['755224','287082','359152','969429','338314','254676','287922','162583','399871','520489'];
check('RFC 4226 HOTP vectors (10 counters)', expected.every((code, i) => hotp(secret, i) === code));
check('RFC 6238 TOTP at T=59s -> 287082', hotp(secret, Math.floor(59 / 30)) === '287082');
check('base32 encode RFC vector', base32Encode(secret) === 'GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ');
check('base32 round trip (random 20 bytes)', (() => { const b = require('crypto').randomBytes(20); return base32Decode(base32Encode(b)).equals(b); })());
const now = Date.now();
check('current code accepted', matchTotp(secret, hotp(secret, currentStep(now)), now) === currentStep(now));
check('previous-step code accepted (clock drift)', matchTotp(secret, hotp(secret, currentStep(now) - 1), now) === currentStep(now) - 1);
check('code 3 steps old rejected', matchTotp(secret, hotp(secret, currentStep(now) - 3), now) === null);
check('non-numeric code rejected', matchTotp(secret, 'abc123', now) === null);
const key = require('crypto').randomBytes(32);
const sealed = encrypt(key, 'JBSWY3DPEHPK3PXP');
check('AES-GCM round trip', decrypt(key, sealed) === 'JBSWY3DPEHPK3PXP');
check('AES-GCM detects tampering', (() => { const b = Buffer.from(sealed, 'base64'); b[b.length - 1] ^= 1; try { decrypt(key, b.toString('base64')); return false; } catch { return true; } })());
check('safeEqual', safeEqual('123456', '123456') && !safeEqual('123456', '123457') && !safeEqual('1', '12'));
console.log(results.join('\n'));
process.exit(results.some((r) => r.startsWith('FAIL')) ? 1 : 0);